version: 0.2
phases:
   install:
      runtime-versions:
         docker: 18
   pre_build:
      commands:
      - echo "Entered the pre-build phase"
      - $(aws ecr get-login  --no-include-email --region $AWS_REGION)
   build:
      commands:
      - echo "Entered build phase"
      - cd AuthorizationMicroservice
      - mvn compile
      - mvn package
      - echo " building docker image"
      - docker build -t service/authsapp .
      - docker tag service/authsapp 430321133782.dkr.ecr.ap-south-1.amazonaws.com/j008-truyum-auth:authsapp
   post_build:
      commands:
      - echo "Entered the post-build phase"
      - docker push 430321133782.dkr.ecr.ap-south-1.amazonaws.com/j008-truyum-auth:authsapp
      - printf '[{"name":"authsapp-container","imageUri":"%s"}]' 430321133782.dkr.ecr.ap-south-1.amazonaws.com/j008-truyum-auth:authsapp>taskdefinition.json
artifacts:
   files:
   - AuthorizationMicroservice/taskdefinition.json